### ISSUE TITLE
No js support results in beyond weird behavior on about page

### ISSUE THREAD

**Issue by samip5** [romeq/usva-ui#3]
![image](https://user-images.githubusercontent.com/1703002/221201215-d92e23a2-e4fe-4858-addc-65a2ef78089f.png)

That window doesn't close automatically. ;)

**Comment by romeq** [comment]
Thank you for creating this issue. I'll fix this ASAP.

**Comment by romeq** [comment]
This is a website-related bug, therefore I'll transfer this to https://github.com/usvacloud/usva-ui

**Comment by romeq** [comment]
I added the following overlay to all pages to indicate the need of Javascript for this website. 
![image](https://user-images.githubusercontent.com/83234299/221302562-6cee1cfb-779e-41f2-9395-9fd80d715258.png)

I'm now closing this issue as the main issue was "weird behavior when without javascript", and that issue is now fixed.
